services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/project
    environment:
      - PORT=8000

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1337
      POSTGRES_DB: url_checker
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: