<!DOCTYPE html>

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Список сайтов</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="min-vh-100 d-flex flex-column">

    <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <?php if (isset($error)): ?>
                <div class="alert alert-danger"><?= htmlspecialchars($error) ?></div>
            <?php endif ?>
            <h1>Сайты</h1>
            <div class="table-responsive">
                <table class="table table-bordered table-hover text-nowrap" data-test="urls">
                    <thead>
                        <tr class="table-success">
                            <th>ID</th>
                            <th>Имя</th>
                            <th>Последняя проверка</th>
                            <th>Код ответа</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($urls as $url): ?>
                            <tr>
                                <td><?= htmlspecialchars($url->getId()) ?></td>
                                <td><a href="/urls/<?= $url->getId() ?>"><?= htmlspecialchars($url->getName()) ?></a></td>
                                <td>
                                    <?= isset($lastChecks[$url->getId()]) 
                                        ? htmlspecialchars($lastChecks[$url->getId()]['created_at']) 
                                        : '' ?>
                                </td>
                                <td>
                                    <?= isset($lastChecks[$url->getId()]) 
                                        ? htmlspecialchars($lastChecks[$url->getId()]['status_code']) 
                                        : '' ?>
                                </td>
                            </tr>
                        <?php endforeach ?>
                    </tbody>
                </table>
            </div>
        </div>
    </main>

    <footer class="border-top py-3 mt-5 bg-success flex-shrink-0 text-white">
        <div class="container-lg text-center">
            Самая большая пицца была приготовлена в 2017 году в Риме — её диаметр составил 40 метров, а вес — более 20 тонн.
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>