<?php if (!empty($flash['success'])) : ?>
    <div class="alert alert-success"><?= htmlspecialchars($flash['success'][0]) ?></div>
<?php endif; ?>
<?php if (!empty($flash['error'])) : ?>
    <div class="alert alert-danger"><?= htmlspecialchars($flash['error'][0]) ?></div>
<?php endif; ?>

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Просмотр URL</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="min-vh-100 d-flex flex-column">
    <main class="flex-grow-1">
<div class="container-lg mt-3">
    <h1>Сайт: <?= htmlspecialchars($url->getName()) ?></h1>
    <div class="table-responsive">
        <table class="table table-bordered table-hover text-nowrap">
            <tbody>
                <tr>
                    <td>ID</td>
                    <td><?= htmlspecialchars($url->getId()) ?></td>
                </tr>
                <tr>
                    <td>Имя</td>
                    <td><?= htmlspecialchars($url->getName()) ?></td>
                </tr>
                <tr>
                    <td>Дата создания</td>
                    <td><?= htmlspecialchars($url->getDate()) ?></td>
                </tr>
            </tbody>
        </table>
    </div>
    <h2 class="mt-5 mb-3">Проверки</h2>
    <form method="post" action="/urls/<?= $url->getId() ?>/checks">
        <button type="submit" class="btn btn-success">Запустить проверку</button>
    </form>
    <?php if (!empty($checkData)): ?>
        <div class="table-responsive mt-3">
            <table class="table table-bordered table-hover" data-test="checks">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Код ответа</th>
                        <th>h1</th>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Дата проверки</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($checkData as $check): ?>
                        <tr>
                            <td><?= htmlspecialchars($check->getId()) ?></td>
                            <td><?= htmlspecialchars($check->getStatusCode()) ?></td>
                            <td><?= htmlspecialchars($check->getH1() ?? '') ?></td>
                            <td><?= htmlspecialchars($check->getTitle() ?? '') ?></td>
                            <td><?= htmlspecialchars($check->getDescription() ?? '') ?></td>
                            <td><?= htmlspecialchars($check->getCheckDate()) ?></td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    <?php endif ?>
</div>
    </main>
    <footer class="border-top py-3 mt-5 bg-success flex-shrink-0 text-white">
        <div class="container-lg text-center">
            Самая большая пицца была приготовлена в 2017 году в Риме — её диаметр составил 40 метров, а вес — более 20 тонн.
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>