<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= htmlspecialchars($pageTitle ?? 'Анализатор страниц') ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="min-vh-100 d-flex flex-column">

    <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <h1>Анализатор страниц</h1>
            <div class="row">
                <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
                    <?php if (isset($errors) && count($errors) > 0): ?>
                        <div class="alert alert-danger" data-test="error">
                            <?php foreach ($errors as $field => $fieldErrors): ?>
                                <?php foreach ($fieldErrors as $error): ?>
                                    <?= htmlspecialchars($error) ?><br>
                                <?php endforeach ?>
                            <?php endforeach ?>
                        </div>
                    <?php endif ?>
                    <form action="/urls" method="post">
                        <div class="form-floating mb-3">
                            <input type="text"
                                   name="url[name]"
                                   class="form-control <?= isset($errors) ? 'is-invalid' : '' ?>"
                                   placeholder="https://www.example.com"
                                   value="<?= htmlspecialchars($url['name'] ?? '') ?>"
                                   required
                                   data-test="url">
                            <label for="url">Адрес страницы</label>
                        </div>
                        <input type="submit" class="btn btn-success" value="Проверить" data-test="submit">
                    </form>
                </div>
            </div>
        </div>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>