<!DOCTYPE html>

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= htmlspecialchars($pageTitle ?? 'Анализатор страниц') ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="min-vh-100 d-flex flex-column">
    <header class="flex-shrink-0">
        <nav class="navbar navbar-expand-md navbar-dark bg-success px-3">
            <a class="navbar-brand" href="/">Анализатор страниц</a>
            <a class="nav-link text-white" href="/urls">Сайты</a>
        </nav>
    </header>

    <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <h1>Анализатор страниц</h1>
            <div class="row">
                <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
                    <?php if (isset($error) && is_string($error)): ?>
                        <div class="alert alert-danger" data-test="error"><?= htmlspecialchars($error) ?></div>
                    <?php endif ?>
                    <form action="/urls" method="post">
                        <div class="form-floating mb-3">
                            <input type="text" 
                                   name="url[name]"
                                   class="form-control <?= isset($error) ? 'is-invalid' : '' ?>"
                                   placeholder="https://www.example.com"
                                   value="<?= htmlspecialchars($url ?? '') ?>"
                                   required
                                   data-test="url">
                            <label for="url">Адрес страницы</label>
                        </div>
                        <input type="submit" class="btn btn-success" value="Проверить" data-test="submit">
                    </form>
                </div>
            </div>
        </div>
    </main>

    <footer class="border-top py-3 mt-5 bg-success flex-shrink-0 text-white">
        <div class="container-lg text-center">
            Самая дорогая пицца была приготовлена в 2006 году в Лос-Анджелесе — её стоимость составляла 12 000 долларов. В состав входили сыр «Буффало», крем из фуа-гра, лосось, омар и зернистая икра осетра.
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>